---
language: node_js
node_js:
  - "4"

sudo: required

services:
  - docker

cache:
  directories:
    - node_modules
    - bower_components

install:
  - docker-compose run --rm npm install
  - docker-compose run --rm bower install

script:
  - docker-compose run --rm npm test
