ember: &defaults
  image: randallmorey/ember-cli-native-support:2.4.3
  command: ['server', '--watcher', 'polling']
  volumes:
    - .:/ember-cli-app
  ports:
    - 4200:4200
    - 49152:49152
fastboot:
  <<: *defaults
  command: ['fastboot', '--serve-assets', '--environment=production']
  volumes:
    - .:/ember-cli-app
  ports:
    - 3000:3000
npm:
  <<: *defaults
  entrypoint: ['/usr/bin/npm']
  command: ['--help']
bower:
  <<: *defaults
  entrypoint: ['/usr/bin/bower', '--allow-root', '--config.interactive=false']
  command: ['--help']
